name: Atualizar Logos no Airtable

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'   # Executa todos os dias às 08h UTC

jobs:
  update-logos:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Clonar repositório
        uses: actions/checkout@v3

      - name: 🟢 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Instalar dependências
        run: npm install
        working-directory: scripts

      - name: 🚀 Executar script de atualização
        run: node update_airtable_logos.js
        working-directory: scripts
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
          